### PR TITLE
Feature/implicit typing

### PR DESCRIPTION
**Pull request by raerpo**
First of all, thanks for this awesome library. It saves a lot of time for a lot of people.

The PR contains two parts:

- Little fix in the README changing the project name. I guess it was based on another project and never gets fix.
- I made some modifications in the type anotations for easier reading. I added the return type on every funcion and remove the type anotations on variables which type is easily inferred by TS compiler. For example:

`let rutDigits: number = parseInt(rut.slice(0, -1), 10);`

TS knows that parseInt always returns a number so its not necessary to type the variable `rutDigits`.

Please let me know if you agree with this changes or if you want me to change anything.

Thanks for your time.

### CODE REVIEW

**Comment by gmq** [comment]
Hi, thanks for the PR!

I'm sorry for the delay in replying, I keep going over this and I'm still not sure what to think about implicit typing. On one hand it makes the code less verbose but on the other I fear it's the beginning of an slippery slope since it's easier to say and check "make all types explicit" than "give types to things that can't be inferred or that are hard to guess".

I'd love to hear more opinions about this, @blackjid @ReneMoraales?

**Comment by antidiestro** [comment]
I don't feel totally comfortable removing the explicit typing. Coming from Angular, I appreciate having a definition of all my properties at the beginning of a class, like so:

image

...my point being that I think it's useful to have a list of all variables and their types available at a glance, without necessarily being distracted by the values being assigned to them. I'm not sure about how this would translate into this particular example, but those are my two cents.

**Comment by raerpo** [comment]
Thank you guys for taking time to review this PR.

surprisingly, i searched some "best practices" for when to relay on type inference and i couldn't find anything so i guess this is more like a personal preference. ¯\_(ツ)_/¯

If you don't feel comfortable by removing the explicit typing maybe i can modify the PR in order to just adding type definition for the functions to make. What do you think?

**Comment by blackjid** [comment]
@ReneMoraales @gmq do you think this is going somewhere? So we can merge eventually? Maybe we should just close it?

**Comment by gmq** [comment]
I'm going to close this PR but feel free to submit a new one with the type definitions for the functions. Thanks!

**Pull request closed without merging**
